[toolchain]
package_manager = "yarn"
anchor_version = "0.32.1" # anchor-cli
solana_version = "2.3.0"  # solana-cli

[features]
resolution = true
skip-lint = false

[programs.localnet]
execution_beacon = "5HKRQJKjw4QkDsFGP4YibxqZWJTyNtSswxXNwdAy6FSi"

[programs.mainnet]
execution_beacon = "BRoueHsu3h2SfEse9ohXipm1R9uRGRSe3zPYsAT8RySr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/solana-deploy-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
